### ISSUE TITLE
请问您目前使用中有遇到什么问题吗？

### ISSUE THREAD

**Issue by tuoniaoren** [hehuapei/ASUS-a550jk-4200---macOS#2]
我想使用您的EFI文件安装一下macos，请问您有记录安装的教程吗。之前没有搞过macos，直接把EFI复制到安装文件中就可以了是吗？

**Comment by hehuapei** [comment]
对,系统安装完成后把efi文件替换掉就可以了

**Comment by tuoniaoren** [comment]
> 对,系统安装完成后把efi文件替换掉就可以了

谢谢您的回复！我自己去尝试着安装一下。

**Comment by tuoniaoren** [comment]
> 对,系统安装完成后把efi文件替换掉就可以了

您好，你遇到过在BIOS设置了u盘启动，也用f10保存设置了，但是启动的时候还是win10启动，我把win10快速启动和安全启动都关闭了，目前第一步u盘启动启动不了。

**Comment by hehuapei** [comment]
> > 对,系统安装完成后把efi文件替换掉就可以了
> 
> 您好，你遇到过在BIOS设置了u盘启动，也用f10保存设置了，但是启动的时候还是win10启动，我把win10快速启动和安全启动都关闭了，目前第一步u盘启动启动不了。

安装教程建议到黑果小兵或者远景论坛,tonymac等网站上面查找哦!

**Comment by tuoniaoren** [comment]
> > > 对,系统安装完成后把efi文件替换掉就可以了
> > 
> > 
> > 您好，你遇到过在BIOS设置了u盘启动，也用f10保存设置了，但是启动的时候还是win10启动，我把win10快速启动和安全启动都关闭了，目前第一步u盘启动启动不了。
> 
> 安装教程建议到黑果小兵或者远景论坛,tonymac等网站上面查找哦!

好的，我拆下电池直接插电就好了，不过第一遍从u盘复制到硬盘上，复制到一半出现一个大的一个圆圈里面一个斜杠，感觉像是我的固态不能用来装黑苹果。

**Comment by tuoniaoren** [comment]
> > > 对,系统安装完成后把efi文件替换掉就可以了
> > 
> > 
> > 您好，你遇到过在BIOS设置了u盘启动，也用f10保存设置了，但是启动的时候还是win10启动，我把win10快速启动和安全启动都关闭了，目前第一步u盘启动启动不了。
> 
> 安装教程建议到黑果小兵或者远景论坛,tonymac等网站上面查找哦!
请问您目前的clover是什么版本的，我安装的黑果小兵的第一个博客的镜像，安装好了系统发现他的clover时5050的，导致我如果用您的就不能开机，用5050的，能进系统但是没有驱动，hd4600显示才3m的显存。再次麻烦您一下。您的clover要是5050的，希望让我copy一下，谢谢了

**Comment by hehuapei** [comment]
> clover

我文件里面就包含clover的,我用的好像是49XX版本
